name: Build & Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Build & Test
      run: |
        npm install
        npm run build --if-present
        npm run test
        npm run coverage
      env:
        CI: true
    - name: Lint
      run: |
        npm run lint
      env:
        CI: true
    - name: coverage
      run: |
        npm run coverage
      env:
        CI: true
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./docs/coverage/lcov.info
